export const ControlErrorCode = {
  INVALID_PATH: "INVALID_PATH",
  UNKNOWN: "UNKNOWN",
  PATH_NOT_FOUND: "PATH_NOT_FOUND",
  PATH_NOT_DIRECTORY: "PATH_NOT_DIRECTORY",
  PATH_ACCESS_DENIED: "PATH_ACCESS_DENIED",
  PROXY_OFFLINE: "PROXY_OFFLINE",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  PROVIDER_UNSUPPORTED: "PROVIDER_UNSUPPORTED",
  WORKER_START_FAILED: "WORKER_START_FAILED",
  PROCESS_START_FAILED: "PROCESS_START_FAILED",
} as const;

export type ControlErrorCodeType = (typeof ControlErrorCode)[keyof typeof ControlErrorCode];
